/**
 * Blank a filled form and generate the bundled preset from it.
 *
 * Input is a document with real data in it, which never leaves this machine and
 * is never committed. Output is a blank copy — every mapped value replaced by
 * its field name, and not a byte of structure changed — plus a generated module
 * carrying that copy and a mapping fingerprinted against it.
 *
 * Uses the same fill engine as the app. Blanking in Word instead would
 * restructure the runs and the mapping would stop fitting.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { readDocx, documentXml } from '../lib/docx/unzip'
import { serialiseDocx } from '../lib/docx/serialise'
import { parseDocument } from '../lib/docx/parse'
import { blankCopy, blankedNodes, residualPersonalData } from '../lib/mapping/sanitise'
import { finaliseDraft } from '../lib/mapping/draft'
import { FORMULIR_CUTI_NAME, FORMULIR_CUTI_TARGETS } from '../lib/presets/formulir-cuti'
import type { ProfileValues } from '../lib/derive/compute'

const input = process.argv[2] ?? 'template.docx'
const outDocx = process.argv[3] ?? 'presets/formulir-cuti-kosong.docx'
const outModule = process.argv[4] ?? 'lib/presets/formulir-cuti.generated.ts'

const read = readDocx(new Uint8Array(readFileSync(input)))
if (read.type !== 'read') throw new Error(`${read.type}: ${read.reason}`)
const parsed = parseDocument(documentXml(read.package))
if (parsed.type !== 'parsed') throw new Error(parsed.reason)

const blank = blankCopy(parsed.document, FORMULIR_CUTI_TARGETS)
if (blank.type !== 'filled') {
  throw new Error(blank.problems.map((problem) => problem.reason).join('\n'))
}

const reparsed = parseDocument(blank.xml)
if (reparsed.type !== 'parsed') throw new Error(reparsed.reason)

// Fingerprinted against the blank copy, which is the document that ships.
const mapping = finaliseDraft(
  { name: FORMULIR_CUTI_NAME, targets: FORMULIR_CUTI_TARGETS },
  reparsed.document,
  { id: 'formulir-cuti', createdAt: '2026-08-21T00:00:00.000Z' },
)
if (mapping.type !== 'ready') throw new Error(mapping.problems.join('\n'))

const bytes = serialiseDocx(read.package, blank.xml)
mkdirSync(dirname(outDocx), { recursive: true })
writeFileSync(outDocx, bytes)

const base64 = Buffer.from(bytes).toString('base64')
mkdirSync(dirname(outModule), { recursive: true })
writeFileSync(
  outModule,
  `// Generated by scripts/blank.mts. Do not edit by hand.
//
// The blank form and the mapping fingerprinted against it, bundled as a module
// rather than fetched — this app makes no network request at runtime, and a
// same-origin fetch is still a fetch.
import type { Mapping } from '../mapping/schema'

export const FORMULIR_CUTI_MAPPING: Mapping = ${JSON.stringify(mapping.mapping, null, 2)
    .split('\n')
    .join('\n')} as const

/** The blank .docx, base64. ${(bytes.length / 1024).toFixed(1)} kB. */
export const FORMULIR_CUTI_DOCX_BASE64 =
  '${base64}'
`,
)

// What the blanking did not reach. Anything still here is in a node the preset
// does not map, and has to be dealt with before the copy is committed.
const profileLike: ProfileValues = JSON.parse(
  readFileSync(process.argv[5] ?? 'scripts/blank-check.json', 'utf8'),
)
const residue = residualPersonalData(
  reparsed.document,
  profileLike,
  blankedNodes(FORMULIR_CUTI_TARGETS),
)

console.log(`blanked  → ${outDocx} (${(bytes.length / 1024).toFixed(1)} kB)`)
console.log(`generated → ${outModule}`)
console.log(`mapping  → ${mapping.mapping.targets.length} targets, ${reparsed.document.textNodes.length} nodes, ${reparsed.document.checkboxCells.length} boxes`)

if (residue.length > 0) {
  console.error(`\n${residue.length} value(s) still present in unmapped nodes:`)
  for (const item of residue) {
    console.error(`  T${String(item.nodeIndex).padStart(3, '0')}  ${item.field}  ${JSON.stringify(item.text)}`)
  }
  process.exitCode = 1
} else {
  console.log('\nno known personal value remains in an unmapped node')
}
