import { zipSync, strToU8 } from 'fflate'

/**
 * A synthetic cuti-shaped template, generated by the suite.
 *
 * No official template ships in this repository — not in fixtures, not in
 * examples, not in the README (invariant 10). This document has the same shape
 * as the real one: Roman-numeraled sections, a data table, checkbox cells that
 * are empty table cells rather than form fields, and a value split across runs
 * because Word does that.
 */

export type SyntheticOptions = {
  /** Perturb the document, for drift tests. */
  readonly variant?: 'baseline' | 'extra-node' | 'edited-label' | 'removed-node'
  /** Include a fake embedded font, to assert byte-for-byte passthrough. */
  readonly withBinaryPart?: boolean
}

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="odttf" ContentType="application/vnd.openxmlformats-officedocument.obfuscatedFont"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`

const RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`

const DOCUMENT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`

const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:styleId="Normal"><w:name w:val="Normal"/></w:style></w:styles>`

function p(...runs: string[]): string {
  return `<w:p><w:pPr><w:pStyle w:val="Normal"/></w:pPr>${runs.join('')}</w:p>`
}

function r(text: string, preserve = false): string {
  const space = preserve ? ' xml:space="preserve"' : ''
  return `<w:r><w:rPr><w:rFonts w:ascii="Arial"/></w:rPr><w:t${space}>${text}</w:t></w:r>`
}

function cell(...body: string[]): string {
  return `<w:tc><w:tcPr><w:tcW w:w="2400" w:type="dxa"/></w:tcPr>${body.join('')}</w:tc>`
}

/** An empty cell — a checkbox target. These carry no <w:t> at all. */
function emptyCell(): string {
  return `<w:tc><w:tcPr><w:tcW w:w="480" w:type="dxa"/></w:tcPr><w:p><w:pPr><w:jc w:val="center"/></w:pPr></w:p></w:tc>`
}

function row(...cells: string[]): string {
  return `<w:tr>${cells.join('')}</w:tr>`
}

function labelledRow(label: string, value: string): string {
  return row(cell(p(r(label))), cell(p(r(':', true))), cell(p(r(value))))
}

function checkboxRow(label: string): string {
  return row(emptyCell(), cell(p(r(label))))
}

export function syntheticDocumentXml(options: SyntheticOptions = {}): string {
  const variant = options.variant ?? 'baseline'
  const jabatanLabel = variant === 'edited-label' ? 'Jabatan / Pangkat' : 'Jabatan'

  const body = [
    p(r('SURAT PERMINTAAN IZIN CUTI')),
    p(r('Nomor: 800/000/BKPSDM/2026')),
    p(r('Balikpapan, 17 Juli 2026')),

    p(r('I. DATA PEGAWAI')),
    `<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>${[
      labelledRow('Nama', 'Nama Pegawai Contoh'),
      labelledRow('NIP', '199001012015011001'),
      labelledRow(jabatanLabel, 'Perekayasa Ahli Pertama'),
      labelledRow('Masa Kerja', '10 tahun 6 bulan'),
      labelledRow('Unit Kerja', 'Direktorat Contoh'),
      ...(variant === 'extra-node' ? [labelledRow('Golongan', 'III/b')] : []),
      ...(variant === 'removed-node' ? [] : [labelledRow('Telepon', '0800-0000-0000')]),
    ].join('')}</w:tbl>`,

    p(r('II. JENIS CUTI YANG DIAMBIL')),
    `<w:tbl><w:tblPr/>${[
      checkboxRow('Cuti Tahunan'),
      checkboxRow('Cuti Besar'),
      checkboxRow('Cuti Sakit'),
      checkboxRow('Cuti Melahirkan'),
      checkboxRow('Cuti Karena Alasan Penting'),
      checkboxRow('Cuti di Luar Tanggungan Negara'),
    ].join('')}</w:tbl>`,

    p(r('III. ALASAN CUTI')),
    p(r('Keperluan keluarga')),

    p(r('IV. LAMANYA CUTI')),
    // A value Word has split across two runs. The mapper must merge these or
    // refuse the target — never write into one half. Invariant 5.
    p(r('Selama '), r('3', true), r(' (tiga) '), r('hari'), r(' kerja')),
    p(r('Mulai tanggal 20 Juli 2026 s/d 22 Juli 2026')),

    p(r('V. CATATAN CUTI')),
    `<w:tbl><w:tblPr/>${[
      labelledRow('Sisa Cuti Tahun Berjalan', '12'),
      labelledRow('Cuti Yang Diambil', '3'),
      labelledRow('Sisa Cuti', '9'),
    ].join('')}</w:tbl>`,

    p(r('VI. ALAMAT SELAMA MENJALANKAN CUTI')),
    p(r('Jl. Contoh No. 1, Balikpapan')),
    p(r('Telp. 0800-0000-0000')),
    p(r('Hormat saya,')),
    p(r('Nama Pegawai Contoh')),

    p(r('VII. PERTIMBANGAN ATASAN LANGSUNG')),
    `<w:tbl><w:tblPr/>${[
      checkboxRow('DISETUJUI'),
      checkboxRow('PERUBAHAN'),
      checkboxRow('DITANGGUHKAN'),
      checkboxRow('TIDAK DISETUJUI'),
    ].join('')}</w:tbl>`,
    p(r('Nama Atasan Contoh')),
    p(r('NIP. 197001011995031001')),

    p(r('VIII. KEPUTUSAN PEJABAT YANG BERWENANG')),
    `<w:tbl><w:tblPr/>${[
      checkboxRow('DISETUJUI'),
      checkboxRow('PERUBAHAN'),
      checkboxRow('DITANGGUHKAN'),
      checkboxRow('TIDAK DISETUJUI'),
    ].join('')}</w:tbl>`,
    p(r('Nama Pejabat Contoh')),
    p(r('NIP. 196501011990031002')),
  ].join('')

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/></w:sectPr></w:body></w:document>`
}

/** A deterministic stand-in for the 5 MB of embedded fonts a real template carries. */
function fakeFontBytes(): Uint8Array {
  const bytes = new Uint8Array(4096)
  for (let i = 0; i < bytes.length; i++) bytes[i] = (i * 31 + 7) % 256
  return bytes
}

/** Build a complete, openable .docx package. */
export function syntheticDocx(options: SyntheticOptions = {}): Uint8Array {
  const files: Record<string, Uint8Array> = {
    '[Content_Types].xml': strToU8(CONTENT_TYPES),
    '_rels/.rels': strToU8(RELS),
    'word/document.xml': strToU8(syntheticDocumentXml(options)),
    'word/_rels/document.xml.rels': strToU8(DOCUMENT_RELS),
    'word/styles.xml': strToU8(STYLES),
  }
  if (options.withBinaryPart ?? true) {
    files['word/fonts/font1.odttf'] = fakeFontBytes()
  }
  return zipSync(files, { mtime: new Date(Date.UTC(1980, 0, 1)).getTime() })
}
